# Generated by Django 4.2.7 on 2026-02-21 10:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('business_type', models.CharField(choices=[('MANUFACTURING', 'Manufacturing'), ('WHOLESALE', 'Wholesale'), ('RETAIL', 'Retail'), ('LOGISTICS', 'Logistics')], max_length=50)),
                ('business_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('shipping_address', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('required_delivery_date', models.DateTimeField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('assigned_to_agent', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'customer_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField(help_text='The goal that triggered this decision')),
                ('order_quantity', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('expected_cost', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('confidence_score', models.DecimalField(decimal_places=2, help_text='AI confidence score (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('explanation', models.JSONField(help_text='Detailed explanation of the decision in JSON format')),
                ('procurement_required', models.BooleanField(db_index=True, default=True)),
                ('inventory_status', models.JSONField(help_text='Snapshot of inventory status at decision time')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'procurement_decisions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterialInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name of the raw material', max_length=255, unique=True)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, help_text='Current stock quantity', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_capacity', models.DecimalField(decimal_places=2, default=1000.0, help_text='Maximum storage capacity', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('reorder_threshold_percentage', models.DecimalField(decimal_places=2, default=25.0, help_text='Percentage threshold for triggering procurement', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'raw_materials_inventory',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0.0, help_text='Price per unit in currency', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('lead_time_days', models.IntegerField(default=7, help_text='Number of days for delivery', validators=[django.core.validators.MinValueValidator(1)])),
                ('reliability_score', models.DecimalField(decimal_places=2, default=75.0, help_text='Reliability score (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material_supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='supply_chain.rawmaterialinventory')),
            ],
            options={
                'db_table': 'vendors',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='rawmaterialinventory',
            index=models.Index(fields=['name'], name='raw_materia_name_ecf306_idx'),
        ),
        migrations.AddIndex(
            model_name='rawmaterialinventory',
            index=models.Index(fields=['-updated_at'], name='raw_materia_updated_b082da_idx'),
        ),
        migrations.AddField(
            model_name='procurementdecision',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_decisions', to='supply_chain.rawmaterialinventory'),
        ),
        migrations.AddField(
            model_name='procurementdecision',
            name='selected_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_decisions', to='supply_chain.vendor'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to='supply_chain.company'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['material_supply', 'is_active'], name='vendors_materia_b17261_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['name'], name='vendors_name_a8eecc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vendor',
            unique_together={('name', 'material_supply')},
        ),
        migrations.AddIndex(
            model_name='procurementdecision',
            index=models.Index(fields=['-created_at'], name='procurement_created_20676c_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementdecision',
            index=models.Index(fields=['raw_material', '-created_at'], name='procurement_raw_mat_3fca44_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementdecision',
            index=models.Index(fields=['procurement_required'], name='procurement_procure_7ddf30_idx'),
        ),
        migrations.AddIndex(
            model_name='customerorder',
            index=models.Index(fields=['order_number'], name='customer_or_order_n_8a1c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='customerorder',
            index=models.Index(fields=['status'], name='customer_or_status_000b68_idx'),
        ),
        migrations.AddIndex(
            model_name='customerorder',
            index=models.Index(fields=['-required_delivery_date'], name='customer_or_require_8fe8a6_idx'),
        ),
    ]
