# Generated by Django 4.2.7 on 2026-02-21 15:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDecisionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision_approved', models.BooleanField(default=True, help_text='Was the AI decision approved by humans?')),
                ('actual_outcome_score', models.DecimalField(blank=True, decimal_places=2, help_text='Actual outcome quality score (0-100)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cost_variance_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Actual cost vs predicted cost variance', max_digits=6)),
                ('delivery_variance_days', models.IntegerField(default=0, help_text='Actual vs predicted delivery time difference')),
                ('user_feedback', models.TextField(blank=True, help_text='Human feedback on the decision')),
                ('lessons_learned', models.JSONField(default=dict, help_text='Structured lessons for ML improvement')),
                ('procurement_decision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='supply_chain.procurementdecision')),
            ],
            options={
                'db_table': 'ai_decision_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorPerformanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_date', models.DateField()),
                ('expected_delivery_date', models.DateField()),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('ordered_quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('delivered_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Actual quantity delivered', max_digits=15, null=True)),
                ('quality_score', models.DecimalField(blank=True, decimal_places=2, help_text='Quality inspection score (0-100)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('on_time_delivery', models.BooleanField(default=False, help_text='Whether delivery was on time or early')),
                ('delivery_delay_days', models.IntegerField(default=0, help_text='Number of days delayed (negative if early)')),
                ('cost_accuracy', models.DecimalField(decimal_places=2, default=100.0, help_text='Percentage accuracy of quoted vs actual cost', max_digits=5)),
                ('issues_reported', models.TextField(blank=True, help_text='Any quality, delivery, or other issues')),
                ('overall_satisfaction', models.DecimalField(decimal_places=2, default=75.0, help_text='Overall satisfaction score (0-100)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('procurement_decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_performance', to='supply_chain.procurementdecision')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_history', to='supply_chain.vendor')),
            ],
            options={
                'db_table': 'vendor_performance_history',
                'ordering': ['-order_date'],
                'indexes': [models.Index(fields=['vendor', '-order_date'], name='vendor_perf_vendor__d4ff25_idx'), models.Index(fields=['on_time_delivery'], name='vendor_perf_on_time_2fc25c_idx'), models.Index(fields=['-order_date'], name='vendor_perf_order_d_ba58e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='SeasonalPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.IntegerField(help_text='Month (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('week_of_month', models.IntegerField(blank=True, help_text='Week within month (optional for fine-grained patterns)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('demand_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplier relative to average (1.5 = 50% higher demand)', max_digits=5)),
                ('average_consumption', models.DecimalField(decimal_places=2, help_text='Average consumption for this period', max_digits=15)),
                ('notes', models.TextField(blank=True, help_text="Reason for pattern (e.g., 'Valentine Day demand spike')")),
                ('confidence_level', models.DecimalField(decimal_places=2, default=75.0, help_text='Confidence in this pattern based on historical data', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_patterns', to='supply_chain.rawmaterialinventory')),
            ],
            options={
                'db_table': 'seasonal_patterns',
                'ordering': ['raw_material', 'month', 'week_of_month'],
                'indexes': [models.Index(fields=['raw_material', 'month'], name='seasonal_pa_raw_mat_81f826_idx')],
                'unique_together': {('raw_material', 'month', 'week_of_month')},
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_date', models.DateField(db_index=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_change_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage change from previous price', max_digits=6)),
                ('reason', models.TextField(blank=True, help_text='Reason for price change (market conditions, etc.)')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='supply_chain.vendor')),
            ],
            options={
                'db_table': 'price_history',
                'ordering': ['-effective_date'],
                'indexes': [models.Index(fields=['vendor', '-effective_date'], name='price_histo_vendor__4bd442_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaterialConsumptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('quantity_consumed', models.DecimalField(decimal_places=2, help_text='Quantity consumed on this date', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('production_volume', models.DecimalField(decimal_places=2, default=0, help_text='Production output on this date', max_digits=15)),
                ('notes', models.TextField(blank=True, help_text='Special events, holidays, etc.')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_history', to='supply_chain.rawmaterialinventory')),
            ],
            options={
                'db_table': 'material_consumption_history',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['raw_material', '-date'], name='material_co_raw_mat_6aacfe_idx'), models.Index(fields=['date'], name='material_co_date_ea4f4c_idx')],
                'unique_together': {('raw_material', 'date')},
            },
        ),
    ]
