# Generated by Django 4.2.7 on 2026-02-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0002_aidecisionfeedback_vendorperformancehistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_type', models.CharField(choices=[('PLANNER', 'Strategic Planner'), ('INVENTORY', 'Inventory Monitor'), ('PROCUREMENT', 'Procurement Specialist'), ('COORDINATOR', 'Supply Chain Coordinator')], help_text='Type of agent (Planner, Inventory, Procurement, Coordinator)', max_length=20)),
                ('agent_id', models.CharField(help_text='Unique identifier for the agent instance', max_length=100)),
                ('status', models.CharField(choices=[('IDLE', 'Idle'), ('ANALYZING', 'Analyzing'), ('PROCESSING', 'Processing'), ('DECIDING', 'Deciding'), ('COMPLETED', 'Completed'), ('ERROR', 'Error')], default='IDLE', help_text='Current status of the agent', max_length=20)),
                ('activity_description', models.TextField(help_text='Human-readable description of what the agent is doing')),
                ('execution_id', models.CharField(blank=True, help_text='ID linking this activity to a specific crew execution', max_length=100)),
                ('goal', models.TextField(blank=True, help_text='The business goal the agent is working on')),
                ('metadata', models.JSONField(default=dict, help_text='Additional data (materials analyzed, vendors evaluated, etc.)')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When the agent started this activity')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the agent completed this activity', null=True)),
                ('duration_seconds', models.FloatField(blank=True, help_text='How long the activity took in seconds', null=True)),
            ],
            options={
                'verbose_name': 'Agent Activity',
                'verbose_name_plural': 'Agent Activities',
                'db_table': 'agent_activity',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['-started_at'], name='agent_activ_started_7cef56_idx'), models.Index(fields=['agent_type', '-started_at'], name='agent_activ_agent_t_219ee3_idx'), models.Index(fields=['execution_id'], name='agent_activ_executi_611aaf_idx')],
            },
        ),
    ]
