# Generated by Django 4.2.7 on 2026-02-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0003_agentactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentactivity',
            name='agent_output',
            field=models.TextField(blank=True, help_text="The actual output/result from the agent's task execution", null=True),
        ),
    ]
