# Generated by Django 4.2.7 on 2026-02-22 11:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0004_add_agent_output'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, help_text='Product name', max_length=255)),
                ('sku', models.CharField(db_index=True, help_text='Stock Keeping Unit - unique product code', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed product description')),
                ('quantity_available', models.DecimalField(decimal_places=2, default=0, help_text='Quantity available for sale', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_reserved', models.DecimalField(decimal_places=2, default=0, help_text='Quantity reserved for pending orders', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Selling price per unit', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_value', models.DecimalField(decimal_places=2, default=0, help_text='Total value (quantity_available * unit_price)', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('raw_materials_used', models.JSONField(blank=True, default=list, help_text='Bill of Materials - list of raw materials used')),
                ('manufacturing_date', models.DateField(help_text='Date of manufacturing')),
                ('expiry_date', models.DateField(blank=True, help_text='Expiry date (if applicable)', null=True)),
                ('warehouse_location', models.CharField(blank=True, help_text='Storage location in warehouse', max_length=255)),
                ('status', models.CharField(choices=[('READY', 'Ready for Sale'), ('RESERVED', 'Reserved for Order'), ('SOLD', 'Sold'), ('RETURNED', 'Returned'), ('QUALITY_HOLD', 'Quality Hold')], db_index=True, default='READY', max_length=20)),
                ('quality_check_status', models.CharField(choices=[('PASSED', 'Quality Passed'), ('FAILED', 'Quality Failed'), ('PENDING', 'Pending QC'), ('REWORK', 'Rework Required')], default='PENDING', max_length=20)),
                ('quality_check_notes', models.TextField(blank=True, help_text='QC inspection notes and findings')),
                ('batch_number', models.CharField(blank=True, help_text='Manufacturing batch number', max_length=100)),
                ('supplier_batch_number', models.CharField(blank=True, help_text='Raw material supplier batch reference', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the product')),
            ],
            options={
                'db_table': 'finish_products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sku'], name='finish_prod_sku_8f3c4f_idx'), models.Index(fields=['status'], name='finish_prod_status_2e3c91_idx'), models.Index(fields=['quality_check_status'], name='finish_prod_quality_f664bc_idx'), models.Index(fields=['-manufacturing_date'], name='finish_prod_manufac_501224_idx'), models.Index(fields=['-created_at'], name='finish_prod_created_2a7f5a_idx')],
            },
        ),
        migrations.CreateModel(
            name='VendorQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity offered by vendor', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('delivery_date', models.DateField(help_text='Expected delivery date')),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Price per unit from vendor', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price (quantity * price_per_unit)', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Calculated discount amount', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('final_price', models.DecimalField(decimal_places=2, help_text='Final price after discount', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('ai_score', models.DecimalField(decimal_places=2, default=0, help_text='Weighted AI score (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ai_analysis', models.JSONField(blank=True, default=dict, help_text='Detailed analysis from AI agents')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Analysis'), ('ANALYZING', 'Being Analyzed'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('source', models.CharField(default='email', help_text='Source of quotation (email, api, manual, etc.)', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the quotation')),
                ('raw_material', models.ForeignKey(help_text='Raw material being quoted', on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='supply_chain.rawmaterialinventory')),
                ('vendor', models.ForeignKey(help_text='Reference to the vendor', on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='supply_chain.vendor')),
            ],
            options={
                'db_table': 'vendor_quotations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor', '-created_at'], name='vendor_quot_vendor__526dd4_idx'), models.Index(fields=['raw_material', '-created_at'], name='vendor_quot_raw_mat_c6781b_idx'), models.Index(fields=['status'], name='vendor_quot_status_3788c9_idx'), models.Index(fields=['-ai_score'], name='vendor_quot_ai_scor_eac41d_idx')],
            },
        ),
    ]
