import type { NavItem, ModuleContentMap } from "../types";

export const NAV_ITEMS: NavItem[] = [
  {
    name: "AI Assistance",
    icon: "✦",
    gradient: "from-violet-500 to-purple-600",
  },
  { name: "Company Info", icon: "◈", gradient: "from-blue-500 to-cyan-600" },
  {
    name: "Raw Inventory",
    icon: "▣",
    gradient: "from-emerald-500 to-teal-600",
  },
  {
    name: "Inventory Vendor",
    icon: "◉",
    gradient: "from-orange-500 to-red-600",
  },
  { name: "Finish Product", icon: "◆", gradient: "from-pink-500 to-rose-600" },
  { name: "Orders", icon: "◎", gradient: "from-indigo-500 to-blue-600" },
  { name: "Logistics", icon: "⟁", gradient: "from-amber-500 to-yellow-600" },
  {
    name: "Logistics Vendor",
    icon: "⊞",
    gradient: "from-slate-500 to-gray-600",
  },
];

export const MODULE_CONTENT: ModuleContentMap = {
  "Company Info": {
    icon: "◈",
    gradient: "from-blue-500 to-cyan-600",
    fields: [
      { label: "Company Name", value: "AcmeCorp Industries Ltd." },
      { label: "Registration No.", value: "REG-2024-00412" },
      { label: "Industry", value: "Manufacturing & Distribution" },
      { label: "Headquarters", value: "Mumbai, Maharashtra, India" },
      { label: "Founded", value: "2008" },
      { label: "GST Number", value: "27AABCU9603R1ZX" },
      { label: "Contact Email", value: "ops@acmecorp.in" },
      { label: "Phone", value: "+91 22 4567 8900" },
    ],
  },
  "Raw Inventory": {
    icon: "▣",
    gradient: "from-emerald-500 to-teal-600",
    tableHeaders: ["Item", "SKU", "Stock", "Unit", "Reorder Level", "Status"],
    tableRows: [
      ["Raw Steel", "RS-001", "2,200 kg", "kg", "3,000 kg", "Low"],
      ["Aluminium Sheet", "AL-012", "5,800 kg", "kg", "2,000 kg", "OK"],
      ["Copper Wire", "CW-045", "320 rolls", "rolls", "100 rolls", "OK"],
      ["Plastic Pellets", "PP-089", "180 bags", "bags", "200 bags", "Low"],
      ["Rubber Seals", "RB-034", "4,500 pcs", "pcs", "1,000 pcs", "OK"],
      ["Carbon Fiber", "CF-007", "60 sheets", "sheets", "50 sheets", "OK"],
    ],
  },
  "Inventory Vendor": {
    icon: "◉",
    gradient: "from-orange-500 to-red-600",
    tableHeaders: [
      "Vendor",
      "Contact",
      "Material",
      "Lead Time",
      "Rating",
      "Status",
    ],
    tableRows: [
      [
        "SteelCo Ltd.",
        "steelco@vendor.in",
        "Raw Steel",
        "4 days",
        "4.8/5",
        "Active",
      ],
      [
        "Alum Partners",
        "alum@vendor.in",
        "Aluminium",
        "6 days",
        "4.5/5",
        "Active",
      ],
      [
        "CopperTrade",
        "copper@vendor.in",
        "Copper Wire",
        "3 days",
        "4.9/5",
        "Active",
      ],
      [
        "PlastiSource",
        "plasti@vendor.in",
        "Plastic Pellets",
        "7 days",
        "4.1/5",
        "Review",
      ],
      [
        "RubberWorld",
        "rubber@vendor.in",
        "Rubber Seals",
        "5 days",
        "4.6/5",
        "Active",
      ],
    ],
  },
  "Finish Product": {
    icon: "◆",
    gradient: "from-pink-500 to-rose-600",
    tableHeaders: [
      "Product",
      "SKU",
      "Units Ready",
      "Units Sold",
      "Target",
      "Status",
    ],
    tableRows: [
      ["Widget Pro X1", "FP-001", "1,200", "980", "1,500", "On Track"],
      ["Connector Unit A", "FP-012", "340", "340", "500", "Behind"],
      ["Steel Frame B2", "FP-033", "2,100", "1,800", "2,000", "Done"],
      ["Flex Module V3", "FP-047", "620", "410", "600", "On Track"],
      ["Base Plate D9", "FP-061", "90", "30", "200", "Behind"],
    ],
  },
  Orders: {
    icon: "◎",
    gradient: "from-indigo-500 to-blue-600",
    tableHeaders: ["Order ID", "Customer", "Items", "Value", "Date", "Status"],
    tableRows: [
      [
        "#ORD-4821",
        "TechBuild Co.",
        "Widget Pro X1 × 50",
        "₹1,24,000",
        "18 Feb 2025",
        "Dispatched",
      ],
      [
        "#ORD-4822",
        "InfraCorp",
        "Steel Frame B2 × 100",
        "₹2,10,000",
        "19 Feb 2025",
        "Processing",
      ],
      [
        "#ORD-4823",
        "Nova Systems",
        "Connector Unit A × 200",
        "₹87,000",
        "20 Feb 2025",
        "Pending",
      ],
      [
        "#ORD-4824",
        "DeltaMfg",
        "Flex Module V3 × 75",
        "₹1,56,000",
        "21 Feb 2025",
        "Confirmed",
      ],
      [
        "#ORD-4825",
        "Alpha Ltd.",
        "Base Plate D9 × 300",
        "₹63,000",
        "21 Feb 2025",
        "Pending",
      ],
    ],
  },
  Logistics: {
    icon: "⟁",
    gradient: "from-amber-500 to-yellow-600",
    tableHeaders: [
      "Shipment ID",
      "Origin",
      "Destination",
      "Carrier",
      "ETA",
      "Status",
    ],
    tableRows: [
      [
        "SHP-9901",
        "Mumbai Warehouse",
        "Delhi Hub",
        "BlueDart",
        "23 Feb 2025",
        "In Transit",
      ],
      [
        "SHP-9902",
        "Pune Plant",
        "Chennai DC",
        "Delhivery",
        "24 Feb 2025",
        "Loaded",
      ],
      [
        "SHP-9903",
        "Mumbai Warehouse",
        "Hyderabad DC",
        "DTDC",
        "25 Feb 2025",
        "Pending",
      ],
      [
        "SHP-9904",
        "Nagpur Depot",
        "Kolkata Hub",
        "FedEx",
        "26 Feb 2025",
        "Scheduled",
      ],
      [
        "SHP-9905",
        "Delhi Hub",
        "Bangalore DC",
        "BlueDart",
        "22 Feb 2025",
        "Delivered",
      ],
    ],
  },
  "Logistics Vendor": {
    icon: "⊞",
    gradient: "from-slate-500 to-gray-600",
    tableHeaders: [
      "Vendor",
      "Coverage",
      "Avg. Delivery",
      "Rate/kg",
      "Rating",
      "Status",
    ],
    tableRows: [
      [
        "BlueDart Express",
        "Pan India",
        "2.1 days",
        "₹18/kg",
        "4.9/5",
        "Preferred",
      ],
      ["Delhivery", "Pan India", "2.8 days", "₹14/kg", "4.5/5", "Active"],
      ["DTDC Courier", "Pan India", "3.2 days", "₹11/kg", "4.2/5", "Active"],
      [
        "FedEx India",
        "Metro + Tier 1",
        "1.8 days",
        "₹24/kg",
        "4.7/5",
        "Active",
      ],
      ["Ecom Express", "Pan India", "3.5 days", "₹10/kg", "3.9/5", "Review"],
    ],
  },
};
