import type { Notification, NotificationTypeConfig } from "../types";

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 1,
    read: false,
    pinned: true,
    type: "critical",
    icon: "🚨",
    title: "Critical Stock Alert",
    body: "Raw Steel inventory has dropped to 18% — below the 25% reorder threshold. Immediate procurement action recommended.",
    module: "Raw Inventory",
    ts: "Just now",
    tsRaw: 0,
    actions: ["View Inventory", "Create PO"],
  },
  {
    id: 2,
    read: false,
    pinned: false,
    type: "ai",
    icon: "✦",
    title: "AI Agent Completed Task",
    body: "Procurement Crew has successfully drafted RFQs for Vendors A, B & C. 3 documents are ready for your review and dispatch.",
    module: "AI Assistance",
    ts: "2 min ago",
    tsRaw: 2,
    actions: ["Review Drafts"],
  },
  {
    id: 3,
    read: false,
    pinned: false,
    type: "order",
    icon: "📦",
    title: "New Order Confirmed",
    body: "Order #ORD-4824 from DeltaMfg for Flex Module V3 × 75 units (₹1,56,000) has been confirmed and queued for processing.",
    module: "Orders",
    ts: "15 min ago",
    tsRaw: 15,
    actions: ["View Order"],
  },
  {
    id: 4,
    read: false,
    pinned: false,
    type: "logistics",
    icon: "🚚",
    title: "Shipment Delayed",
    body: "SHP-9902 from Pune Plant to Chennai DC via Delhivery is delayed by 1 day. New ETA: 25 Feb 2025. Carrier citing traffic disruptions.",
    module: "Logistics",
    ts: "42 min ago",
    tsRaw: 42,
    actions: ["Track Shipment", "Notify Customer"],
  },
  {
    id: 5,
    read: true,
    pinned: false,
    type: "vendor",
    icon: "🤝",
    title: "Vendor Quote Received",
    body: "SteelCo Ltd. has responded to your RFQ with a quote of ₹84/kg for Raw Steel — 6% lower than last order. Valid until 28 Feb 2025.",
    module: "Inventory Vendor",
    ts: "1 hr ago",
    tsRaw: 60,
    actions: ["View Quote", "Accept"],
  },
  {
    id: 6,
    read: true,
    pinned: false,
    type: "finance",
    icon: "💰",
    title: "PO Budget Threshold Warning",
    body: "Monthly procurement budget is at 78% utilization (₹3.9L / ₹5L). Finance Agent suggests deferring non-critical orders.",
    module: "Company Info",
    ts: "2 hr ago",
    tsRaw: 120,
    actions: ["View Budget"],
  },
  {
    id: 7,
    read: true,
    pinned: false,
    type: "system",
    icon: "⚙️",
    title: "System Sync Complete",
    body: "All ERP modules have been successfully synchronized. Inventory, Orders, and Logistics data are up to date as of 08:00 AM today.",
    module: "System",
    ts: "3 hr ago",
    tsRaw: 180,
    actions: [],
  },
  {
    id: 8,
    read: true,
    pinned: false,
    type: "order",
    icon: "✅",
    title: "Order Dispatched",
    body: "Order #ORD-4821 for TechBuild Co. (Widget Pro X1 × 50) has been dispatched via BlueDart. Expected delivery: 23 Feb 2025.",
    module: "Orders",
    ts: "5 hr ago",
    tsRaw: 300,
    actions: ["View Tracking"],
  },
];

export const NOTIF_TYPE_CONFIG: Record<string, NotificationTypeConfig> = {
  critical: {
    bg: "from-rose-500/20 to-red-500/10",
    border: "border-rose-500/40",
    badge: "bg-rose-500",
    label: "Critical",
    labelColor: "text-rose-400",
  },
  ai: {
    bg: "from-violet-500/20 to-purple-500/10",
    border: "border-violet-500/40",
    badge: "bg-violet-500",
    label: "AI Agent",
    labelColor: "text-violet-400",
  },
  order: {
    bg: "from-indigo-500/20 to-blue-500/10",
    border: "border-indigo-500/40",
    badge: "bg-indigo-500",
    label: "Order",
    labelColor: "text-indigo-400",
  },
  logistics: {
    bg: "from-amber-500/20 to-yellow-500/10",
    border: "border-amber-500/40",
    badge: "bg-amber-500",
    label: "Logistics",
    labelColor: "text-amber-400",
  },
  vendor: {
    bg: "from-orange-500/20 to-red-400/10",
    border: "border-orange-500/40",
    badge: "bg-orange-500",
    label: "Vendor",
    labelColor: "text-orange-400",
  },
  finance: {
    bg: "from-emerald-500/20 to-teal-500/10",
    border: "border-emerald-500/40",
    badge: "bg-emerald-500",
    label: "Finance",
    labelColor: "text-emerald-400",
  },
  system: {
    bg: "from-slate-500/20 to-gray-500/10",
    border: "border-slate-500/40",
    badge: "bg-slate-500",
    label: "System",
    labelColor: "text-slate-400",
  },
};
